# Generated by Django 2.0.7 on 2018-07-19 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=100, verbose_name="Caller's name")),
                ('phone_number', models.CharField(max_length=20, verbose_name="Caller's phone number")),
                ('details', models.CharField(max_length=255, verbose_name='Details of enquiry')),
                ('response', models.CharField(blank=True, max_length=255, null=True, verbose_name='Action taken')),
                ('date_quoted', models.DateTimeField(verbose_name='Date quote was sent')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='General remarks')),
                ('status', models.CharField(choices=[('New', 'New enquiry not yet seen'), ('Handling', 'In contact with client, not yet quoted'), ('Quoted', 'Quote sent to client, awaiting response'), ('Closed - Accepted', 'Client accepted quote'), ('Closed - Not Accepted', 'Client refused or did not reply'), ('Closed - Not Quoted', 'We could not help client')], max_length=30, verbose_name='Status of enquiry')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date enquiry created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of last update')),
                ('who_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
